services:

  web:
    image: php:8-apache
    container_name: php-apache-container
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html
    restart: always
    command: bash -c "docker-php-ext-install pdo pdo_pgsql && apache2-foreground"
    depends_on:
      - db
    networks:
      - postgres-network

  db:
    image: postgres:15
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    networks:
      - postgres-network

networks:
  postgres-network:

volumes:
  postgres-data:
