services:
  web:
    build: .
    container_name: php-apache-container
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html
    restart: always
    depends_on:
      - db
    networks:
      - mysql-phpmyadmin

  db:
    platform: linux/x86_64
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin: